In [1]:
print("Python working")

Python working

In [2]:
import pandas as pd
import numpy as np

In [3]:
import pandas as pd  # Import pandas for data manipulation
import numpy as np  # Import numpy for numerical operations

In [4]:
project = pd.DataFrame({
    'ID': ['A001','A002','A003','A004','A005','A002','A005','A003','A001','A003','A001','A004','A004','A005'],
    'Project': ['Project 1','Project 2','Project 3','Project 4','Project 5','Project 6','Project 7','Project 8','Project 9','Project 10','Project 11','Project 12','Project 13','Project 14'],
    'Cost': [1002000,2000000,4500000,5500000,None,680000,400000,350000,None,300000,2000000,1000000,3000000,200000],
    'Status': ['Finished','Ongoing','Finished','Ongoing','Finished','Failed','Finished','Failed','Ongoing','Finished','Failed','Ongoing','Finished','Finished']
}) # Create Project dataframe from given data

In [5]:
project

      ID     Project       Cost    Status
0   A001   Project 1  1002000.0  Finished
1   A002   Project 2  2000000.0   Ongoing
2   A003   Project 3  4500000.0  Finished
3   A004   Project 4  5500000.0   Ongoing
4   A005   Project 5        NaN  Finished
5   A002   Project 6   680000.0    Failed
6   A005   Project 7   400000.0  Finished
7   A003   Project 8   350000.0    Failed
8   A001   Project 9        NaN   Ongoing
9   A003  Project 10   300000.0  Finished
10  A001  Project 11  2000000.0    Failed
11  A004  Project 12  1000000.0   Ongoing
12  A004  Project 13  3000000.0  Finished
13  A005  Project 14   200000.0  Finished

In [6]:
employee = pd.DataFrame({
    'ID': ['A001','A002','A003','A004','A005'],
    'Name': ['John Alter','Alice Luxumberg','Tom Sabestine','Nina Adgra','Amy Johny'],
    'Gender': ['M','F','M','F','F'],
    'City': ['Paris','London','Berlin','Newyork','Madrid'],
    'Age': [25,27,29,31,30]
}) # Create employee dataframe from given data

In [7]:
employee

     ID             Name Gender     City  Age
0  A001       John Alter      M    Paris   25
1  A002  Alice Luxumberg      F   London   27
2  A003    Tom Sabestine      M   Berlin   29
3  A004       Nina Adgra      F  Newyork   31
4  A005        Amy Johny      F   Madrid   30

In [8]:
seniority = pd.DataFrame({
    'ID': ['A001','A002','A003','A004','A005'],
    'Designation Level': [2,2,3,2,3]
}) # Create seniority dataframe from given data

In [9]:
seniority

     ID  Designation Level
0  A001                  2
1  A002                  2
2  A003                  3
3  A004                  2
4  A005                  3

In [10]:
project.to_csv('project.csv', index=False)
employee.to_csv('employee.csv', index=False)
seniority.to_csv('seniority.csv', index=False) # Save project, employee, seniority data to CSV file

In [11]:
for i in range(len(project)):
    if pd.isna(project.loc[i, 'Cost']):
        project.loc[i, 'Cost'] = project['Cost'][:i].mean()

In [12]:
project

      ID     Project       Cost    Status
0   A001   Project 1  1002000.0  Finished
1   A002   Project 2  2000000.0   Ongoing
2   A003   Project 3  4500000.0  Finished
3   A004   Project 4  5500000.0   Ongoing
4   A005   Project 5  3250500.0  Finished
5   A002   Project 6   680000.0    Failed
6   A005   Project 7   400000.0  Finished
7   A003   Project 8   350000.0    Failed
8   A001   Project 9  2210312.5   Ongoing
9   A003  Project 10   300000.0  Finished
10  A001  Project 11  2000000.0    Failed
11  A004  Project 12  1000000.0   Ongoing
12  A004  Project 13  3000000.0  Finished
13  A005  Project 14   200000.0  Finished

In [13]:
employee[['First Name','Last Name']] = employee['Name'].str.split(' ', expand=True) # Split full name into first and last name columns

In [14]:
employee.drop('Name', axis=1, inplace=True) # Remove original Name column after splitting

In [15]:
final = pd.merge(project, employee, on='ID') # Merge project and employee data using ID

In [16]:
final = pd.merge(final, seniority, on='ID') # Merge previous result with seniority data using ID

In [17]:
final

,ID,Project,Cost,Status,Gender,City,Age,First Name,Last Name,Designation Level
0,A001,Project 1,1002000.0,Finished,M,Paris,25,John,Alter,2
1,A002,Project 2,2000000.0,Ongoing,F,London,27,Alice,Luxumberg,2
2,A003,Project 3,4500000.0,Finished,M,Berlin,29,Tom,Sabestine,3
3,A004,Project 4,5500000.0,Ongoing,F,Newyork,31,Nina,Adgra,2
4,A005,Project 5,3250500.0,Finished,F,Madrid,30,Amy,Johny,3
5,A002,Project 6,680000.0,Failed,F,London,27,Alice,Luxumberg,2
6,A005,Project 7,400000.0,Finished,F,Madrid,30,Amy,Johny,3
7,A003,Project 8,350000.0,Failed,M,Berlin,29,Tom,Sabestine,3
8,A001,Project 9,2210312.5,Ongoing,M,Paris,25,John,Alter,2
9,A003,Project 10,300000.0,Finished,M,Berlin,29,Tom,Sabestine,3
10,A001,Project 11,2000000.0,Failed,M,Paris,25,John,Alter,2
11,A004,Project 12,1000000.0,Ongoing,F,Newyork,31,Nina,Adgra,2
12,A004,Project 13,3000000.0,Finished,F,Newyork,31,Nina,Adgra,2
13,A005,Project 14,200000.0,Finished,F,Madrid,30,Amy,Johny,3

In [18]:
final['Bonus'] = np.where(final['Status'] == 'Finished',
                          final['Cost'] * 0.05,
                          0)  # Give 5% bonus if project is finished, else 0

In [19]:
final

,ID,Project,Cost,Status,Gender,City,Age,First Name,Last Name,Designation Level,Bonus
0,A001,Project 1,1002000.0,Finished,M,Paris,25,John,Alter,2,50100.0
1,A002,Project 2,2000000.0,Ongoing,F,London,27,Alice,Luxumberg,2,0.0
2,A003,Project 3,4500000.0,Finished,M,Berlin,29,Tom,Sabestine,3,225000.0
3,A004,Project 4,5500000.0,Ongoing,F,Newyork,31,Nina,Adgra,2,0.0
4,A005,Project 5,3250500.0,Finished,F,Madrid,30,Amy,Johny,3,162525.0
5,A002,Project 6,680000.0,Failed,F,London,27,Alice,Luxumberg,2,0.0
6,A005,Project 7,400000.0,Finished,F,Madrid,30,Amy,Johny,3,20000.0
7,A003,Project 8,350000.0,Failed,M,Berlin,29,Tom,Sabestine,3,0.0
8,A001,Project 9,2210312.5,Ongoing,M,Paris,25,John,Alter,2,0.0
9,A003,Project 10,300000.0,Finished,M,Berlin,29,Tom,Sabestine,3,15000.0
10,A001,Project 11,2000000.0,Failed,M,Paris,25,John,Alter,2,0.0
11,A004,Project 12,1000000.0,Ongoing,F,Newyork,31,Nina,Adgra,2,0.0
12,A004,Project 13,3000000.0,Finished,F,Newyork,31,Nina,Adgra,2,150000.0
13,A005,Project 14,200000.0,Finished,F,Madrid,30,Amy,Johny,3,10000.0

In [20]:
final.loc[final['Status'] == 'Failed', 'Designation Level'] -= 1 # Decrease designation level by 1

In [21]:
final = final[final['Designation Level'] <= 4]

In [22]:
final

,ID,Project,Cost,Status,Gender,City,Age,First Name,Last Name,Designation Level,Bonus
0,A001,Project 1,1002000.0,Finished,M,Paris,25,John,Alter,2,50100.0
1,A002,Project 2,2000000.0,Ongoing,F,London,27,Alice,Luxumberg,2,0.0
2,A003,Project 3,4500000.0,Finished,M,Berlin,29,Tom,Sabestine,3,225000.0
3,A004,Project 4,5500000.0,Ongoing,F,Newyork,31,Nina,Adgra,2,0.0
4,A005,Project 5,3250500.0,Finished,F,Madrid,30,Amy,Johny,3,162525.0
5,A002,Project 6,680000.0,Failed,F,London,27,Alice,Luxumberg,1,0.0
6,A005,Project 7,400000.0,Finished,F,Madrid,30,Amy,Johny,3,20000.0
7,A003,Project 8,350000.0,Failed,M,Berlin,29,Tom,Sabestine,2,0.0
8,A001,Project 9,2210312.5,Ongoing,M,Paris,25,John,Alter,2,0.0
9,A003,Project 10,300000.0,Finished,M,Berlin,29,Tom,Sabestine,3,15000.0
10,A001,Project 11,2000000.0,Failed,M,Paris,25,John,Alter,1,0.0
11,A004,Project 12,1000000.0,Ongoing,F,Newyork,31,Nina,Adgra,2,0.0
12,A004,Project 13,3000000.0,Finished,F,Newyork,31,Nina,Adgra,2,150000.0
13,A005,Project 14,200000.0,Finished,F,Madrid,30,Amy,Johny,3,10000.0

In [23]:
final['First Name'] = np.where(final['Gender'] == 'M',
                              'Mr. ' + final['First Name'],
                              'Mrs. ' + final['First Name']) # Assign Mr. for males and Mrs. for females

In [24]:
final.drop('Gender', axis=1, inplace=True)

In [25]:
final

,ID,Project,Cost,Status,City,Age,First Name,Last Name,Designation Level,Bonus
0,A001,Project 1,1002000.0,Finished,Paris,25,Mr. John,Alter,2,50100.0
1,A002,Project 2,2000000.0,Ongoing,London,27,Mrs. Alice,Luxumberg,2,0.0
2,A003,Project 3,4500000.0,Finished,Berlin,29,Mr. Tom,Sabestine,3,225000.0
3,A004,Project 4,5500000.0,Ongoing,Newyork,31,Mrs. Nina,Adgra,2,0.0
4,A005,Project 5,3250500.0,Finished,Madrid,30,Mrs. Amy,Johny,3,162525.0
5,A002,Project 6,680000.0,Failed,London,27,Mrs. Alice,Luxumberg,1,0.0
6,A005,Project 7,400000.0,Finished,Madrid,30,Mrs. Amy,Johny,3,20000.0
7,A003,Project 8,350000.0,Failed,Berlin,29,Mr. Tom,Sabestine,2,0.0
8,A001,Project 9,2210312.5,Ongoing,Paris,25,Mr. John,Alter,2,0.0
9,A003,Project 10,300000.0,Finished,Berlin,29,Mr. Tom,Sabestine,3,15000.0
10,A001,Project 11,2000000.0,Failed,Paris,25,Mr. John,Alter,1,0.0
11,A004,Project 12,1000000.0,Ongoing,Newyork,31,Mrs. Nina,Adgra,2,0.0
12,A004,Project 13,3000000.0,Finished,Newyork,31,Mrs. Nina,Adgra,2,150000.0
13,A005,Project 14,200000.0,Finished,Madrid,30,Mrs. Amy,Johny,3,10000.0

In [26]:
final.loc[final['Age'] > 29, 'Designation Level'] += 1 # Increase designation level by 1 if age is more than 29

In [27]:
final

,ID,Project,Cost,Status,City,Age,First Name,Last Name,Designation Level,Bonus
0,A001,Project 1,1002000.0,Finished,Paris,25,Mr. John,Alter,2,50100.0
1,A002,Project 2,2000000.0,Ongoing,London,27,Mrs. Alice,Luxumberg,2,0.0
2,A003,Project 3,4500000.0,Finished,Berlin,29,Mr. Tom,Sabestine,3,225000.0
3,A004,Project 4,5500000.0,Ongoing,Newyork,31,Mrs. Nina,Adgra,3,0.0
4,A005,Project 5,3250500.0,Finished,Madrid,30,Mrs. Amy,Johny,4,162525.0
5,A002,Project 6,680000.0,Failed,London,27,Mrs. Alice,Luxumberg,1,0.0
6,A005,Project 7,400000.0,Finished,Madrid,30,Mrs. Amy,Johny,4,20000.0
7,A003,Project 8,350000.0,Failed,Berlin,29,Mr. Tom,Sabestine,2,0.0
8,A001,Project 9,2210312.5,Ongoing,Paris,25,Mr. John,Alter,2,0.0
9,A003,Project 10,300000.0,Finished,Berlin,29,Mr. Tom,Sabestine,3,15000.0
10,A001,Project 11,2000000.0,Failed,Paris,25,Mr. John,Alter,1,0.0
11,A004,Project 12,1000000.0,Ongoing,Newyork,31,Mrs. Nina,Adgra,3,0.0
12,A004,Project 13,3000000.0,Finished,Newyork,31,Mrs. Nina,Adgra,3,150000.0
13,A005,Project 14,200000.0,Finished,Madrid,30,Mrs. Amy,Johny,4,10000.0

In [28]:
total_cost = final.groupby(['ID','First Name'])['Cost'].sum().reset_index() # Calculate total cost of projects for each employee ID

In [29]:
total_cost.rename(columns={'Cost':'Total Cost'}, inplace=True)

In [30]:
total_cost

     ID  First Name  Total Cost
0  A001    Mr. John   5212312.5
1  A002  Mrs. Alice   2680000.0
2  A003     Mr. Tom   5150000.0
3  A004   Mrs. Nina   9500000.0
4  A005    Mrs. Amy   3850500.0

In [31]:
result = final[final['City'].str.contains('o', case=False)] # Filter rows where city name contains letter 'o'

In [32]:
result

,ID,Project,Cost,Status,City,Age,First Name,Last Name,Designation Level,Bonus
1,A002,Project 2,2000000.0,Ongoing,London,27,Mrs. Alice,Luxumberg,2,0.0
3,A004,Project 4,5500000.0,Ongoing,Newyork,31,Mrs. Nina,Adgra,3,0.0
5,A002,Project 6,680000.0,Failed,London,27,Mrs. Alice,Luxumberg,1,0.0
11,A004,Project 12,1000000.0,Ongoing,Newyork,31,Mrs. Nina,Adgra,3,0.0
12,A004,Project 13,3000000.0,Finished,Newyork,31,Mrs. Nina,Adgra,3,150000.0